// Karta — all Azure resources for one deployment.
//
// Scope: resource group (rg-karta-prod, Sweden Central). Everything the app needs lives here,
// so a single budget and a single `az group delete` cover the whole system.
//
// Deploy:
//   az deployment group create -g rg-karta-prod -f infra/main.bicep -p infra/main.bicepparam
//
// Resource ordering note (CORS <-> SWA):
//   The blob CORS rule has to name the Static Web App's hostname, so `blobSvc` reads
//   `swa.properties.defaultHostname`. That is a one-pass reference: `swa` is declared *before*
//   the blob service and ARM therefore creates the SWA first and only then applies CORS.
//   `defaultHostname` is assigned at SWA creation time, so the very first deployment already
//   writes the real origin — no second pass is required. Extra origins (a custom domain, a
//   long-lived preview environment) go through `additionalAllowedOrigins`, which is the only
//   reason to re-run the deployment.

targetScope = 'resourceGroup'

@description('Azure region for all resources.')
param location string = 'swedencentral'

@description('Short app name. Used for the storage account prefix and the SWA name.')
// Storage names are capped at 24 characters: 'st' + appName + a 13-character uniqueString.
@minLength(3)
@maxLength(9)
param appName string = 'karta'

@description('GitHub repository that GitHub Actions deploys from, e.g. https://github.com/sam/karta.')
param repositoryUrl string

@description('Branch that deploys to production.')
param branch string = 'main'

@description('Origins allowed to talk to blob storage on top of the SWA hostname and the Vite dev server. Add a custom domain here.')
param additionalAllowedOrigins array = []

@description('Addresses that receive the budget alerts.')
@minLength(1)
param contactEmails array

@description('Monthly budget for this resource group, in the billing account currency (100 SEK per the spec).')
param monthlyBudgetAmount int = 100

@description('First day of the month the budget starts tracking. Defaults to the current month; a monthly budget cannot start before it.')
param budgetStartDate string = utcNow('yyyy-MM-01')

var storageName = toLower('st${appName}${uniqueString(resourceGroup().id)}')
var boardsContainer = 'boards'
var mediaContainer = 'media'
var snapshotsContainer = 'snapshots'
var containerNames = [boardsContainer, mediaContainer, snapshotsContainer]

// ---------------------------------------------------------------------------
// Static Web App (Free) — declared first so the CORS rule below can name it.
// ---------------------------------------------------------------------------

resource swa 'Microsoft.Web/staticSites@2023-12-01' = {
  name: 'swa-${appName}'
  location: location
  sku: {
    name: 'Free'
    tier: 'Free'
  }
  properties: {
    // The repository is recorded for reference only. Deployment happens through
    // .github/workflows/azure-static-web-apps.yml with the deployment token, so no
    // repositoryToken is stored here and no workflow is generated by Azure.
    repositoryUrl: repositoryUrl
    branch: branch
    allowConfigFileUpdates: true
    stagingEnvironmentPolicy: 'Enabled'
    buildProperties: {
      appLocation: '/'
      apiLocation: 'api'
      outputLocation: 'dist'
    }
  }
}

// ---------------------------------------------------------------------------
// Storage — board documents, media, snapshots. Hot tier only (see spec 2).
// ---------------------------------------------------------------------------

resource sa 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageName
  location: location
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    // Media is read through account-key SAS minted by the API, so shared key access stays on.
    allowSharedKeyAccess: true
    defaultToOAuthAuthentication: false
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
    publicNetworkAccess: 'Enabled'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
    }
  }
}

resource blobSvc 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: sa
  name: 'default'
  properties: {
    // Undo of last resort. Costs fractions of a cent at this volume; spec 11 says it stays on.
    deleteRetentionPolicy: {
      enabled: true
      days: 14
    }
    containerDeleteRetentionPolicy: {
      enabled: true
      days: 14
    }
    // Off deliberately — the snapshots container is the explicit, predictable history.
    isVersioningEnabled: false
    cors: {
      corsRules: [
        {
          // SWA production hostname + the Vite dev server, plus anything the caller adds.
          allowedOrigins: union(['https://${swa.properties.defaultHostname}', 'http://localhost:5173'], additionalAllowedOrigins)
          allowedMethods: ['GET', 'PUT', 'HEAD', 'OPTIONS']
          allowedHeaders: [
            'x-ms-blob-type'
            'x-ms-blob-content-type'
            'content-type'
            'cache-control'
          ]
          exposedHeaders: ['etag']
          maxAgeInSeconds: 3600
        }
      ]
    }
  }
}

resource containers 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = [
  for name in containerNames: {
    parent: blobSvc
    name: name
    properties: {
      publicAccess: 'None'
    }
  }
]

// ---------------------------------------------------------------------------
// SWA application settings — the managed Functions read these as env vars.
// The storage key lives here rather than in Key Vault; see spec 4.3. Rotate manually.
// ---------------------------------------------------------------------------

resource swaSettings 'Microsoft.Web/staticSites/config@2023-12-01' = {
  parent: swa
  name: 'appsettings'
  properties: {
    STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=${sa.name};AccountKey=${sa.listKeys().keys[0].value};EndpointSuffix=${environment().suffixes.storage}'
    STORAGE_ACCOUNT_NAME: sa.name
    BOARDS_CONTAINER: boardsContainer
    MEDIA_CONTAINER: mediaContainer
    SNAPSHOTS_CONTAINER: snapshotsContainer
  }
}

// ---------------------------------------------------------------------------
// Budget — a tripwire, not a control. Resource-group scoped, so it is declared in this
// resource-group-scoped deployment with no explicit scope property.
// ---------------------------------------------------------------------------

resource budget 'Microsoft.Consumption/budgets@2023-05-01' = {
  name: 'budget-${appName}-monthly'
  properties: {
    category: 'Cost'
    amount: monthlyBudgetAmount
    timeGrain: 'Monthly'
    timePeriod: {
      startDate: budgetStartDate
    }
    notifications: {
      Actual_GreaterThan_50_Percent: {
        enabled: true
        operator: 'GreaterThan'
        threshold: 50
        thresholdType: 'Actual'
        contactEmails: contactEmails
      }
      Actual_GreaterThan_80_Percent: {
        enabled: true
        operator: 'GreaterThan'
        threshold: 80
        thresholdType: 'Actual'
        contactEmails: contactEmails
      }
      Actual_GreaterThan_100_Percent: {
        enabled: true
        operator: 'GreaterThanOrEqualTo'
        threshold: 100
        thresholdType: 'Actual'
        contactEmails: contactEmails
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Outputs
// ---------------------------------------------------------------------------

@description('Storage account holding boards, media and snapshots.')
output storageAccountName string = sa.name

@description('Static Web App resource name — pass to `az staticwebapp secrets list`.')
output swaName string = swa.name

@description('Production hostname, also the origin allowed by the blob CORS rule.')
output swaDefaultHostname string = swa.properties.defaultHostname

@description('Production URL.')
output swaUrl string = 'https://${swa.properties.defaultHostname}'
